dictionaries:
  - en
  - en_GB

excluded_files:
  - "web/settings/*"
  - ".github/*"
  - "requirements*.txt"

excluded_words:
  - addopts
  - backends
  - bleson
  - djhuey
  - esac
  - grafana
  - huey
  - pytz
  - ruuvi
  - ruuvihub
  - ruuvitag
  - ruuvitags
  - urlpatterns
  - uwsgi
  - venv
  - wsgi

spellcheck_filenames: true