dictionaries:
  - en
  - en_GB

excluded_files:
  - "web/settings/*"
  - ".github/*"
  - "requirements*.txt"

excluded_words:
  - ruuvi
  - ruuvihub
  - ruuvitag
  - ruuvitags
  - grafana
  - uwsgi
  - wsgi
  - esac
  - urlpatterns
  - pytz
  - venv

spellcheck_filenames: true