version: '3.7'

services:
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ".${ENV:-dev}.env"
    ports:
      - "5432:5432"

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    command: bash -c "./startup.sh"
    restart: always
    volumes:
      - .:/app
    env_file:
      - ".${ENV:-dev}.env"
    environment:
      - DOCKER=1
      - ENV=${ENV}
    ports:
      - "8000:8000"
    depends_on:
      - db

  web-debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    command: bash -c "./startup.sh"
    volumes:
      - .:/app
    env_file:
      - ".${ENV:-dev}.env"
    environment:
      - DOCKER=1
      - ENV=${ENV}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: