version: '3.7'

services:
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    env_file:
      - "environments/.${ENV:-dev}.env"
    ports:
      - "5432:5432"

  web-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    command: bash -c "./scripts/startup.sh"
    restart: always
    volumes:
      - .:/app
    env_file:
      - "environments/.${ENV:-test}.env"
    environment:
      - ENV=${ENV}
    ports:
      - "8000:8000"
    depends_on:
      - db

  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "./scripts/startup.sh"
    volumes:
      - .:/app
    env_file:
      - "environments/.${ENV:-dev}.env"
    environment:
      - ENV=${ENV:-dev}
    ports:
      - "8000:8000"
    depends_on:
      - db

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - ENV=${ENV:-dev}
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - db

volumes:
  postgres_data:
  grafana-data: