version: '3'

services:
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "./startup.sh"
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: