version: '3.7'

services:
  
  web-db:
    image: postgres
    volumes:
      - web-db-data:/var/lib/postgresql/data/
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    env_file: .env
    environment:
      - POSTGRES_NAME=${WEB_DB_NAME}
      - POSTGRES_USER=${WEB_DB_USER}
      - POSTGRES_PASSWORD=${WEB_DB_PASSWORD}
      - POSTGRES_HOST=${WEB_DB_HOST}
      - POSTGRES_PORT=${WEB_DB_PORT}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "./scripts/django-startup.sh"
    restart: always
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - web-db

  grafana-db:
    image: postgres
    volumes:
      - grafana-db-data:/var/lib/postgresql/data/
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    env_file: .env
    environment:
      - POSTGRES_NAME=${GRAFANA_DB_NAME}
      - POSTGRES_USER=${GRAFANA_DB_USER}
      - POSTGRES_PASSWORD=${GRAFANA_DB_PASSWORD}
      - POSTGRES_HOST=${GRAFANA_DB_HOST}
      - POSTGRES_PORT=${GRAFANA_DB_PORT}


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
    - grafana-data:/var/lib/grafana
    - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - grafana-db

volumes:
  web-db-data:
  grafana-db-data:
  grafana-data: