# Generated by Django 3.0.6 on 2020-05-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sensor',
            field=models.ForeignKey(default='ba68f421-fef3-4d0d-b647-156c510caf5a', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ruuvitags.Sensor'),
            preserve_default=False,
        ),
    ]
