# Generated by Django 3.0.5 on 2020-04-12 11:03

import django.core.validators
from django.db import migrations, models
import web.ruuvitags.models


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='sensor_id',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), web.ruuvitags.models.is_sensor_id]),
        ),
    ]
