# Generated by Django 3.0.6 on 2020-05-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0002_auto_20200520_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='mac_address',
            new_name='mac',
        ),
    ]
