# Generated by Django 3.0.5 on 2020-04-12 11:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import web.ruuvitags.models


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0002_auto_20200412_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[web.ruuvitags.models.is_json_deserializable]),
        ),
    ]
