# Generated by Django 3.0.6 on 2020-05-26 15:02

import django.core.validators
from django.db import migrations, models
import web.ruuvitags.models


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0003_auto_20200526_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mac',
            field=models.CharField(max_length=17, validators=[web.ruuvitags.models.is_mac]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), web.ruuvitags.models.is_mac]),
        ),
    ]
