# Generated by Django 3.0.6 on 2020-05-11 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid
import web.ruuvitags.models


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0003_auto_20200509_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ruuvitags.Sensor'),
        ),
        migrations.CreateModel(
            name='StructuredEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_format', models.IntegerField(choices=[(5, 'Five')])),
                ('humidity', models.DecimalField(decimal_places=15, max_digits=28)),
                ('temperature', models.DecimalField(decimal_places=15, max_digits=28)),
                ('pressure', models.DecimalField(decimal_places=15, max_digits=28)),
                ('acceleration', models.DecimalField(decimal_places=15, max_digits=28)),
                ('acceleration_x', models.IntegerField()),
                ('acceleration_y', models.IntegerField()),
                ('acceleration_z', models.IntegerField()),
                ('tx_power', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('movement_counter', models.IntegerField()),
                ('measurement_sequence_number', models.IntegerField()),
                ('mac', models.CharField(max_length=12, validators=[web.ruuvitags.models.is_mac])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruuvitags.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
