# Generated by Django 3.0.6 on 2020-05-28 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import web.ruuvitags.models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Sensor = apps.get_model('ruuvitags', 'Sensor')
    Location = apps.get_model('ruuvitags', 'Location')
    Event = apps.get_model('ruuvitags', 'Event')
    db_alias = schema_editor.connection.alias
    for sensor in Sensor.objects.using(db_alias).all():
        location = Location(name=f'location-for-{sensor.name}', sensor=sensor)
        location.save()
        events_to_update = Event.objects.using(db_alias).filter(sensor=sensor)
        events_to_update.update(location=location)


class Migration(migrations.Migration):

    dependencies = [
        ('ruuvitags', '0004_auto_20200526_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.TextField(default=web.ruuvitags.models.get_location_name, help_text='A user editable identifier for a location.', unique=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='ruuvitags.Sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ruuvitags.Location'),
        ),
        migrations.RunPython(forwards_func, None),
        migrations.RemoveField(
            model_name='event',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='events', to='ruuvitags.Location'),
        ),
    ]
