#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${GRAFANA_USER} WITH PASSWORD '${GRAFANA_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${GRAFANA_USER};
    GRANT USAGE ON SCHEMA public TO ${GRAFANA_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${GRAFANA_USER};
    GRANT pg_read_all_stats TO ${GRAFANA_USER};
    GRANT pg_read_all_settings TO ${GRAFANA_USER};
    GRANT pg_monitor TO ${GRAFANA_USER};
EOSQL
