name: Validate

on:
  push:
    branches:
      - main
  # Run tests for all PRs.
  pull_request:

env:
  ENV: test

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image if available
        run: docker pull docker.pkg.github.com/${{ github.repository }}/web:latest || true

      - name: Build Docker image
        run: |
          cp -n .sample.env .env
          CACHE_FROM=docker.pkg.github.com/${{ github.repository }}/web:latest docker-compose build web

      - name: Run Django check
        run: docker-compose run web python manage.py check

      - name: Run linters
        run: docker-compose run web flake8 .

      - name: Run tests
        run: docker-compose run web python manage.py test -v 2

      - name: Push Docker image
        run: |
          docker tag ruuvihub_web docker.pkg.github.com/${{ github.repository }}/web:latest
          docker push docker.pkg.github.com/${{ github.repository }}/web:latest
