name: Validate

on:
  push:
    branches:
      - master
  # Run tests for all PRs.
  pull_request:

env:
  ENV: test

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: docker-compose build web-prod

      - name: Run Django check
        run: docker-compose run web-prod python manage.py check

      - name: Run linters
        run: docker-compose run web-prod flake8 .

      - name: Run tests
        run: docker-compose run web-prod python manage.py test -v 2

